### ISSUE TITLE
Debian 9 /Stretch support??

### ISSUE THREAD

**Issue by hvisage** [mendix/m2ee-tools#14]
Good day,

 just following up on the possibility of Stretch/Debian 9 packages?

**Comment by djvdorp** [comment]
+1

**Comment by knorrie** [comment]
Yes, of course. The current Jessie packages just work on Stretch. I copied them in the Mendix debian packages repository.

**Comment by knorrie** [comment]
I also updated the list in the first page of the documentation. (develop branch)
