### ISSUE TITLE
m2ee (adjust) loglevel does not work if the lognodename has a space in it

### ISSUE THREAD

**Issue by djvdorp** [mendix/m2ee-tools#15]
Today I was trying to set the `loglevel` for the following `lognodename`: `REST Consume`
However, the Python cli input validation/parsing for the m2ee cli doesn't seem to like this, no matter what I do, it doesn't accept it. I tried adding it as displayed, with `'` and with `"` but to no avail.

```
m2ee(tr10000): loglevel
Current loglevels:

syslogsubscriber RestConsume INFO

To adjust loglevels, use: loglevel <subscribername> <lognodename> <level>
Available levels: NONE, CRITICAL, ERROR, WARNING, INFO, DEBUG, TRACE
```

```
m2ee(tr10000): loglevel syslogsubscriber REST Consume TRACE
To adjust loglevels, use: loglevel <subscribername> <lognodename> <level>
Available levels: NONE, CRITICAL, ERROR, WARNING, INFO, DEBUG, TRACE

m2ee(tr10000): loglevel syslogsubscriber 'REST Consume' TRACE
To adjust loglevels, use: loglevel <subscribername> <lognodename> <level>
Available levels: NONE, CRITICAL, ERROR, WARNING, INFO, DEBUG, TRACE

m2ee(tr10000): loglevel syslogsubscriber "REST Consume" TRACE
To adjust loglevels, use: loglevel <subscribername> <lognodename> <level>
Available levels: NONE, CRITICAL, ERROR, WARNING, INFO, DEBUG, TRACE
```

Ideally, your `lognodename` should probably not contain spaces, but I can not imagine that I am the only one that experiences this. The reason why I suspect this is the cli input validation/parsing is that I think it would result in perfectly fine JSON from what I can tell, however you never get to that point:

```
$ m2ee -vvvv
m2ee(tr10000): loglevel syslogsubscriber RestConsume TRACE
TRACE: Executing command: loglevel syslogsubscriber REST Consume TRACE
TRACE: M2EE request body: {"action": "set_log_level", "params": {"subscriber": "syslogsubscriber", "node": "REST Consume", "level": "TRACE"}}
TRACE: M2EE response: {"feedback":{},"result":0}
INFO: Loglevel for RestConsume set to TRACE
```

**Comment by knorrie** [comment]
I'm suprised that the names actually allow you to put in spaces. I don't think that's a good idea.

The cli parsing is just simple string split. It's not advanced quoting detection etc like your shell does.

**Comment by djvdorp** [comment]
Agreed, that is a fair point. Allowing `lognodenames` with spaces doesn't sound like a good idea to me either.
The only reason I stumbled upon it, was that I had to enable it for `REST Consume` in this case.

Maybe the right thing to do here would be to see if we can prevent people from creating `lognodenames` like that in the first place?

**Comment by djvdorp** [comment]
As discussed, https://pymotw.com/2/shlex/ could do the trick.

One could look where args split is done in the cli command parsing, and see where it makes sense to use shlex split instead. Also e.g. for unpack_mda. But then one has to fix the autocomplete also :)

**Comment by djvdorp** [comment]
A (temporary) workaround if you hit these issues, is to change this in `core.py`:

```
    def set_log_level(self, subscriber, node, level):
        params = {"subscriber": subscriber, "node": node, "level": level}
        return self.client.set_log_level(params)
```

To

```
    def set_log_level(self, subscriber, node, level):
        params = {"subscriber": subscriber, "node": node.replace('__', ' '), "level": level}
        return self.client.set_log_level(params)
```

Then you can use `m2ee loglevel syslogsubscriber REST__Consume TRACE` to actually execute `m2ee loglevel syslogsubscriber REST Consume TRACE` but this is very ugly and hackish and no fix.

**Comment by knorrie** [comment]
For loglevel, I pushed a commit in develop branch.

Unpack would indeed be the other candidate for improvement. I looked at it but the effort needed to make autocomplete work is too big relative to the gain to make it interesting to work on. Besides that, if you have a weird loglevel, you cannot fix that easily since it's inside the running app. If you have a mda with a weird name, you can easily rename it yourself.
