### ISSUE TITLE
Specify runtime path instead of give possible locations

### ISSUE THREAD

**Issue by jtwaleson** [mendix/m2ee-tools#32]
For debugging/runtime CI purposes, it would be good to be able to say: use runtime path `/srv/app/runtimes/x.y.z` instead of "look for the runtime in `/srv/app/runtimes/`".

Usecase: the runtime wants to run CI on cloud foundry / docker and also ship the runtime dev build along with the MDA.

**Comment by knorrie** [comment]
Closing since I don't know what to do with this, don't know who actually requested it in the first place and since it doesn't seem to be active, and I'm not looking for more work just for fun. :)
