### ISSUE TITLE
m2ee start - timeout setting??

### ISSUE THREAD

**Issue by hvisage** [mendix/m2ee-tools#34]
Goodday,

so, busy with Ansible deploys, and I have errors with database connectivity, which causes the `m2ee start` to hang indefinitely.

The errors that scrolls through the log file:

> 2018-03-26 15:52:33.022 WARNING - ConnectionBus: Database connections: 0 active, 0 idle.
>2018-03-26 15:52:33.022 ERROR - ConnectionBus: Opening JDBC connection to Some(192.168.200.22:5432) failed with SQLState: 08001 Error code: 0 Message: Connection to 192.168.200.22:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections., giving up...(4/4)

Yes, I also have a 2nd JDBC connection (where the Mendix App in this case fetches data to populate the  "main"/modeller database).

What I'm in need of, is a sorta time-out for the start to fail with some errors if the Mendix doesn't start up in time.
This might be to consider in the light of things like model (database structure) changes that does take a long(er) time to complete...

**Comment by knorrie** [comment]
Included in v7.2-rc1
