### ISSUE TITLE
Debian 11 (Bullseye) packages "empty"

### ISSUE THREAD

**Issue by hvisage** [mendix/m2ee-tools#56]
busy testing/setting up Debian 11 Mendix instances, and the bullseye distribution seems empty, had to fall back to buster to get packages, but these have other python2 related problems it seem when trying to install `m2ee-tools`

```
The following packages have unmet dependencies:
 python-m2ee : Depends: python-yaml but it is not installable
               Depends: python-httplib2 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by knorrie** [comment]
Hi! Yes, it's a shame.

The good news is that I'm actually working on this (when not being distracted by operational work).

The version will bump to v9, to signal it's compatible with starting the Mendix Runtime up to v9.x, it's Python 3 only now, and I'm taking the opportunity of the major version bump to also clean out some really old code, swap out some dependencies and clean up parts of the documentation.

Hans

**Comment by hevisko** [comment]
PS: while doing that, perhaps a 7.2.3-1 with 7.2.3 version info as the 7.2.3.tar.gz seemed to think it's still 7.2.2:

```
acw2@agw-acw-mx01-prod ~ % m2ee about
Using m2ee-tools version 7.2.2
Using Mendix Runtime version 8.18.14.33751
Copyright © 2003-2021 Mendix bv. All rights reserved.
Model version: 3.0.0.1432
acw2@agw-acw-mx01-prod ~ % ls
acw2  m2ee-tools-7.2.3  mx-build.sh  rr.awk
acw2@agw-acw-mx01-prod ~/m2ee-tools-7.2.3
 % find . -type f | xargs grep 7.2.3
./CHANGES:m2ee-tools 7.2.3, 18 Oct 2021
acw2@agw-acw-mx01-prod ~/m2ee-tools-7.2.3
 % find . -type f | xargs grep 7.2.2
./src/m2ee/__init__.py:__version__ = '7.2.2'
./CHANGES:m2ee-tools 7.2.2, 21 Mar 2019
```

**Comment by hvisage** [comment]
don't like to hasten, but as I'm busy rebuilding an brand new Debian 11, any eta on a bulls eye package?

**Comment by richardburleigh** [comment]
> don't like to hasten, but as I'm busy rebuilding an brand new Debian 11, any eta on a bulls eye package?

I'm coming late to this, so I assume you have solved the problem, however you can run m2ee-tools directly from python if the package install failed.
