### ISSUE TITLE
Where to find empty-4.1.0.mda?

### ISSUE THREAD

**Issue by aihua** [mendix/m2ee-tools#58]
Where to find the empty-4.1.0.mda file in  [Configuring the application](https://github.com/mendix/m2ee-tools/blob/master/doc/configure.md)? Can you provide it?

**Comment by hvisage** [comment]
Why not just create your own?

> For testing purpose, I've created a minimal application in the Mendix 4.1.0 modeler, called empty, exported for deployment to empty-4.1.0.mda.

**Comment by aihua** [comment]
> Why not just create your own?
> 
> > For testing purpose, I've created a minimal application in the Mendix 4.1.0 modeler, called empty, exported for deployment to empty-4.1.0.mda.
> 
> besides, you can now do it in the Mx9/8/7/6 modeler instead of the ancient 4 ;)

Oh, we will try it then. 
It would be better to update the document.

**Comment by knorrie** [comment]
Thanks for your feedback. I understand why you might be running into this confusing problem.

The documentation could indeed be improved. We could also provide a super-minimal Mendix application "Hello, world" model export using the latest supported version that would start without problems.

However, if you got the task to set up a server to run a Mendix application, then one of the most important things you should be doing is to walk over to the team that has the task to actually build the application.

What you can ask them to do is "hey! while you're also busy... I'm setting up the server environment. And I need something simple that I can use to test it." It's totally OK to ask them to create some separate Hello World application, to help you out.
