### ISSUE TITLE
Error while starting app:

### ISSUE THREAD

**Issue by bartrikers** [mendix/m2ee-tools#8]
Hello,
I'm trying to start an on-premise Mendix app, but I get the following error:

`m2ee(mxlaba): start
INFO: Trying to start the MxRuntime...
Traceback (most recent call last):
  File "/usr/bin/m2ee", line 1071, in <module>
    cli.cmdloop()
  File "/usr/lib64/python2.6/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib64/python2.6/cmd.py", line 219, in onecmd
    return func(arg)
  File "/usr/bin/m2ee", line 69, in do_start
    self._start()
  File "/usr/bin/m2ee", line 133, in _start
    if not self.m2ee.start_appcontainer():
  File "/usr/share/m2ee-tools/m2ee/core.py", line 86, in start_appcontainer
    if not self.runner.start():
  File "/usr/share/m2ee-tools/m2ee/runner.py", line 155, in start
    self._pid = proc.pid
UnboundLocalError: local variable 'proc' referenced before assignment
ERROR: Starting the JVM process did not succeed...`

We're using Mx 6.7.1, and m2ee version 0.5.11.3...

Do you have any idea what the problem could be?

Thanks!

**Comment by xiwenc** [comment]
Can you try with python 2.7 or later?

**Comment by bartrikers** [comment]
Thanks for the reply, we have indeed specified a custom javabin in the yaml, because java1.8 is not installed systemwide. Is this correctly specified in the yaml like this?

![jfdk1 8](https://cloud.githubusercontent.com/assets/23105910/19801918/6bae5668-9d01-11e6-8765-79633871e9a0.png)
![yaml](https://cloud.githubusercontent.com/assets/23105910/19801917/6bae15cc-9d01-11e6-9bcb-d1044adf3590.png)

**Comment by xiwenc** [comment]
`javabin` should be absolute path to the java executable (or symlink) *not* the java directory

**Comment by bartrikers** [comment]
Thanks, it's working now!
